### ISSUE TITLE
Open the calendar on focus rather than icon click or enter?

### ISSUE THREAD

**Issue by duffyjp** [airblade/stimulus-datepicker#13]
Basically the title-- is it possible to have the calendar automatically show and hide based on the text field focus rather than a click?

**Comment by airblade** [comment]
I've been following the [WAI-ARIA date picker dialog](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html) design pattern, and I understand it to mean the calendar should show and hide based on clicking (or the keyboard equivalent) the toggle button.

Having said that, I just re-read the pattern and it doesn't really specify one way or the other.  I think it used to but they seem to have updated it since I built the datepicker.  Their example code still requires clicking a toggle button.

Anyway, you could listen for the text field's focus event and then trigger a click event on the toggle element.  Either with plain JavaScript or a tiny Stimulus controller of your own.

**Comment by hmontazeri** [comment]
you actually can't bc the click event trigger on toggle will close the datepicker again 😢 just tried 😃

**Comment by airblade** [comment]
Thanks @hmontazeri.  I'm going to close this because I don't think the calendar should behave this way by default, and it's straightforward to handle the event if you really want to.
