### ISSUE TITLE
Does not display dates before the year 2000

### ISSUE THREAD

**Issue by bkroeker** [airblade/stimulus-datepicker#7]
Any time I use the datepicker to pick a date before 2000-01-01, the input element does not display the date.  This happens on the demo page too. 
https://airblade.github.io/stimulus-datepicker/

If I provide the input element with a value like "1999-12-31", I can briefly see the text inside the input element before it disappears again. 

```html
<!-- good -->
<input data-datepicker-target="input" type="text" value="2000-01-01" name="user[birthdate]" />

<!-- bad -->
<input data-datepicker-target="input" type="text" value="1999-12-31" name="user[birthdate]" />
```

**Comment by airblade** [comment]
Thanks for reporting this.

When I was writing the code to handle a 2-digit year, I decided to handle it as a year in the 21st century.  And that somehow got stuck in my head when I was validating the year value.

The fix is in v0.0.7, which I just pushed, but it normally takes the CDNs an hour or so to update.
